CREATE TABLE historical_product
(
    historical_product_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_product_id    BIGINT NOT NULL,
    update_date           TIMESTAMP WITHOUT TIME ZONE,
    price                 DECIMAL,
    CONSTRAINT pk_historicalproduct PRIMARY KEY (historical_product_id)
);

CREATE TABLE product
(
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code       VARCHAR(255) NOT NULL UNIQUE ,
    name       VARCHAR(255) NOT NULL UNIQUE ,
    active     BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT pk_product PRIMARY KEY (product_id)
);

CREATE TABLE product_sale
(
    product_sale_id                          BIGINT  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sale_id                                  BIGINT,
    historical_product_historical_product_id BIGINT,
    quantity                                 INTEGER NOT NULL,
    CONSTRAINT pk_productsale PRIMARY KEY (product_sale_id)
);

CREATE TABLE sale
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date   TIMESTAMP WITHOUT TIME ZONE,
    amount DECIMAL,
    CONSTRAINT pk_sale PRIMARY KEY (id)
);

ALTER TABLE historical_product
    ADD CONSTRAINT FK_HISTORICALPRODUCT_ON_PRODUCT_PRODUCTID FOREIGN KEY (product_product_id) REFERENCES product (product_id);

ALTER TABLE product_sale
    ADD CONSTRAINT FK_PRODUCTSALE_ON_HISTORICALPRODUCT_HISTORICALPRODUCTID FOREIGN KEY (historical_product_historical_product_id) REFERENCES historical_product (historical_product_id);

ALTER TABLE product_sale
    ADD CONSTRAINT FK_PRODUCTSALE_ON_SALE FOREIGN KEY (sale_id) REFERENCES sale (id);
